export const LEVELS = [
    { minCoins: 0, name: "Seed", emoji: "🌱" },
    { minCoins: 100, name: "Sprout", emoji: "🌿" },
    { minCoins: 200, name: "Sapling", emoji: "🌾" },
    { minCoins: 500, name: "Young Tree", emoji: "🌳" },
    { minCoins: 700, name: "Blooming Tree", emoji: "🌸" },
    { minCoins: 1000, name: "Fruiting Tree", emoji: "🍎" },
    { minCoins: 2000, name: "Sacred Grove", emoji: "🌲" },
    { minCoins: 5000, name: "Ancient Tree", emoji: "🌴" },
    { minCoins: 7000, name: "Enlightened Tree", emoji: "🧘‍♂️" },
    { minCoins: 9000, name: "Tree of Light", emoji: "✨🌳" },
  ];
  

  export const LEVEL_PROGRESSION = [
    { subLevel: "Locked", category: "Beginner", minDays: 1, maxDays: 6 },
    { subLevel: "Brass 1", category: "Brass Bravery", minDays: 7, maxDays: 10 },
    { subLevel: "Brass 2", category: "Brass Bravery", minDays: 11, maxDays: 14 },
    { subLevel: "Brass 3", category: "Brass Bravery", minDays: 15, maxDays: 19 },
    { subLevel: "Brass 4", category: "Brass Bravery", minDays: 20, maxDays: 25 },
    { subLevel: "Brass 5", category: "Brass Bravery", minDays: 26, maxDays: 32 },
    { subLevel: "Iron 1", category: "Iron Will", minDays: 33, maxDays: 40 },
    { subLevel: "Iron 2", category: "Iron Will", minDays: 41, maxDays: 49 },
    { subLevel: "Iron 3", category: "Iron Will", minDays: 50, maxDays: 59 },
    { subLevel: "Iron 4", category: "Iron Will", minDays: 60, maxDays: 70 },
    { subLevel: "Iron 5", category: "Iron Will", minDays: 71, maxDays: 82 },
    { subLevel: "Copper 1", category: "Copper Glow", minDays: 83, maxDays: 95 },
    { subLevel: "Copper 2", category: "Copper Glow", minDays: 96, maxDays: 109 },
    { subLevel: "Copper 3", category: "Copper Glow", minDays: 110, maxDays: 124 },
    { subLevel: "Copper 4", category: "Copper Glow", minDays: 125, maxDays: 140 },
    { subLevel: "Copper 5", category: "Copper Glow", minDays: 141, maxDays: 157 },
    { subLevel: "Silver 1", category: "Silver Peace", minDays: 158, maxDays: 175 },
    { subLevel: "Silver 2", category: "Silver Peace", minDays: 176, maxDays: 194 },
    { subLevel: "Silver 3", category: "Silver Peace", minDays: 195, maxDays: 214 },
    { subLevel: "Silver 4", category: "Silver Peace", minDays: 215, maxDays: 235 },
    { subLevel: "Silver 5", category: "Silver Peace", minDays: 236, maxDays: 257 },
    { subLevel: "Gold 1", category: "Gold Harmony", minDays: 258, maxDays: 280 },
    { subLevel: "Gold 2", category: "Gold Harmony", minDays: 281, maxDays: 304 },
    { subLevel: "Gold 3", category: "Gold Harmony", minDays: 305, maxDays: 329 },
    { subLevel: "Gold 4", category: "Gold Harmony", minDays: 330, maxDays: 355 },
    { subLevel: "Gold 5", category: "Gold Harmony", minDays: 356, maxDays: 364 },
    { subLevel: "Divine 1", category: "Divine Radiance", minDays: 365, maxDays: 729 },
    { subLevel: "Divine 2", category: "Divine Radiance", minDays: 730, maxDays: Infinity },
  ];