export const firstStreakMessages = [
    "🎉 You've just started your journey with {challengeName}—1 day down, and many more to go!",
    "🚀 First step complete! 1 day of {challengeName}, you’re off to a great start!",
    "🌟 Your first {challengeName} streak — 1 day down! Keep going, you’ve got this!",
    "💪 You've completed your first {challengeName} streak! Day 1 is just the beginning!",
    "🎯 Day 1 of {challengeName} — the first of many! Keep up the great work!",
    "🔥 Boom! You’re on fire already! 1 day of {challengeName} done, let's make it a streak!",
    "✨ Congratulations! Day 1 of {challengeName} is in the books! You're already on the path to success!",
    "🎉 1 day of {challengeName} done! What a way to start, keep that energy going!",
    "🚴 You've completed your first {challengeName} streak—1 day strong! Keep pushing forward!",
    "🥳 One down, many more to go! You’ve completed 1 day of {challengeName} — let's keep it rolling!"
  ];
  

  export const motivationalMessages = [
    "🔥 Incredible! {challengeName} streak of {streak} days — you're unstoppable! +{coinsEarned} coins!",
    "🎯 Nailed it! {streak} days straight on {challengeName}! Keep shining! +{coinsEarned} coins!",
    "🏆 Champion alert! {streak} days {challengeName} streak — beast mode activated! +{coinsEarned} coins!",
    "💪 Stronger every day! {streak} days of {challengeName} completed! +{coinsEarned} coins!",
    "🌟 Superstar! {challengeName} for {streak} days straight — keep inspiring! +{coinsEarned} coins!",
    "🚀 Skyrocketing! {challengeName} streak for {streak} days — your consistency is magic! +{coinsEarned} coins!",
    "🥇 Medal deserved! {streak} days on {challengeName} — absolutely killing it! +{coinsEarned} coins!",
    "📈 Level up! {challengeName} streak of {streak} days is legendary! +{coinsEarned} coins!",
    "🔥 Fire mode! {challengeName} {streak} days — not everyone can do what you just did! +{coinsEarned} coins!",
    "🌈 Making dreams real! {streak} days practicing {challengeName}! +{coinsEarned} coins!",
    "✨ Magic in motion! {challengeName} completed for {streak} days! +{coinsEarned} coins!",
    "🎉 Celebration time! {challengeName} {streak} days streak, +{coinsEarned} coins richer!",
    "🏋️ Power builder! {streak} days of {challengeName} — you’ve built a strong habit! +{coinsEarned} coins!",
    "💥 Boom! {challengeName} completed for {streak} days! +{coinsEarned} coins!",
    "🌍 You’re inspiring the world with {challengeName} streak of {streak} days! +{coinsEarned} coins!",
    "🚴 Keep moving! {challengeName} streak: {streak} days strong! +{coinsEarned} coins!",
    "🌻 Blooming habits! {streak} days of {challengeName} — beautiful work! +{coinsEarned} coins!",
    "🎬 Daily action hero: {streak} days on {challengeName}! +{coinsEarned} coins!",
    "🧘 Inner peace champion! {challengeName} {streak} days streak! +{coinsEarned} coins!",
    "🦸 Super you! {challengeName} for {streak} days, hero! +{coinsEarned} coins!",
    "🎶 Perfect rhythm! {challengeName} streak: {streak} days flowing! +{coinsEarned} coins!",
    "📚 Learned and earned! {challengeName} completed for {streak} days! +{coinsEarned} coins!",
    "🌟 Legend unlocked! {streak} days on {challengeName}! +{coinsEarned} coins!",
    "🛡️ Warrior spirit! {challengeName} {streak} days in a row! +{coinsEarned} coins!",
    "🪄 Magical streak! {challengeName} day {streak}! +{coinsEarned} coins!",
    "💖 Self-love streak! {challengeName} {streak} days strong! +{coinsEarned} coins!",
    "💥 Explosive progress! {streak} days of {challengeName} — you’re unstoppable! +{coinsEarned} coins!",
  "🔥 Legendary streak! {streak} days of {challengeName}, keep pushing! +{coinsEarned} coins!",
  "🌟 You’re rewriting the rulebook with {streak} days of {challengeName}! +{coinsEarned} coins!",
  "🥇 World champion vibes! {challengeName} streak of {streak} days and counting! +{coinsEarned} coins!",
  "🎯 Consistency king! {streak} days of {challengeName} is pure focus! +{coinsEarned} coins!",
  "⚡ Unstoppable momentum! {challengeName} streak for {streak} days! +{coinsEarned} coins!",
  "🌱 Growing stronger with each day! {streak} days of {challengeName}! +{coinsEarned} coins!",
  "🏅 Victory lap! {streak} days in a row on {challengeName}! +{coinsEarned} coins!",
  "🌍 Your dedication to {challengeName} is a global inspiration! {streak} days streak! +{coinsEarned} coins!",
  "🛠️ Building the habit of a lifetime — {streak} days of {challengeName}! +{coinsEarned} coins!",
  "🚀 You’re on another level! {challengeName} streak of {streak} days! +{coinsEarned} coins!",
  "🛡️ Unbeatable! {streak} days of {challengeName} — solid habits, stronger you! +{coinsEarned} coins!",
  "⚔️ Ready for anything! {challengeName} streak of {streak} days — warrior mode on! +{coinsEarned} coins!",
  "🧗 Climbing to the top! {streak} days on {challengeName} — you’re unstoppable! +{coinsEarned} coins!",
  "🏆 You’ve reached new heights! {streak} days of {challengeName} — you’re a champion! +{coinsEarned} coins!",
  "✨ You’ve made {streak} days of {challengeName} look easy! +{coinsEarned} coins!",
  "🔥 Blaze through! {streak} days of {challengeName} done! Keep igniting that fire! +{coinsEarned} coins!",
  "📈 Breaking records! {challengeName} streak: {streak} days strong! +{coinsEarned} coins!",
  "🎉 Keep going! {streak} days of {challengeName} — amazing consistency! +{coinsEarned} coins!",
  "💫 Keep soaring! {challengeName} streak for {streak} days — you're going places! +{coinsEarned} coins!"
  ];